name: vxdetector
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - flake8
  - pytest
  - coverage >= 6  # to ensure lcov option is available
  - pandas
  - samtools
  - bedtools
  - bowtie2
